repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: system

      - id: ruff-format-check
        name: ruff-format-check
        entry: ruff format --check
        language: system

      - id: mypy
        name: mypy
        entry: mypy src/
        language: system
        pass_filenames: false
