repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check src/ tests/
        language: system
        stages: [pre-push]
        pass_filenames: false
        require_serial: true

      - id: ruff-format-check
        name: ruff-format-check
        entry: ruff format --check src/ tests/
        language: system
        stages: [pre-push]
        pass_filenames: false
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy src/
        language: system
        stages: [pre-push]
        pass_filenames: false
        require_serial: true
