#!/usr/bin/env bash
# Auto-generated by bootstrap.sh
uvx --quiet --from "context-store-mcp[all] @ git+https://github.com/yohi/chronos-graph.git" \
  chronos-mcp-gateway evaluate \
  --json-io \
  --policy-path "${CHRONOS_EVALUATOR_POLICY_PATH:-$HOME/.config/chronos/intents.yaml}"
